### ISSUE TITLE
Few questions regarding the "distribution over union" behaviour discussed in `Item 53`

### ISSUE THREAD

**Issue by som-sm** [danvk/effective-typescript#39]
Thanks a lot for writing this amazing book, it has been a wonderful experience reading it 🙏🏻

# Doubts in `Item 53`

## Preventing the "distribution over union" behaviour messes up instantiations with `never`

So, there's this `Comparable` generic in [Item 53](https://github.com/danvk/effective-typescript/blob/main/samples/ch-generics/control-distribution.md) which shows us a situation where we'd want to opt of the "distribution over union" behaviour.

```ts
type Comparable<T> =
    [T] extends [Date] ? Date | number:
    [T] extends [number] ? number :
    [T] extends [string] ? string :
    never;
```

Now that we've prevented the distribution behaviour, we've also messed up how `never` is handled. So, if we now instantiate `Comparable` with `never` it returns `Date | number` whereas previously (before preventing the distribution) it returned `never`.

```ts
type Test = Comparable<never>;
//   ^? Test = number | Date
```

Feels like we should handle the `never` case and ensure that it returns `never`, probably by adding an extra `[T] extends [never]` check?

```ts
type Comparable<T> =
    [T] extends [never] ? never:
    [T] extends [Date] ? Date | number:
    [T] extends [number] ? number :
    [T] extends [string] ? string :
    never;

type Test = Comparable<never>;
//   ^? Test = never
```

<hr />

And a very similar thing happens with the `CelebrateIfTrue` generic further down in [Item 53](https://github.com/danvk/effective-typescript/blob/main/samples/ch-generics/control-distribution.md).

So, here also we've prevented the distribution because we didn't want `boolean` to get distributed, but now if `CelebrateIfTrue` is instantiated with `never` it returns `'Huzzah!'` instead of `never`, which again probably requires an additional `[V] extends [never]` check.

```ts
type CelebrateIfTrue<V> = [V] extends [true] ? 'Huzzah!' : never;

type SurpriseParty = CelebrateIfTrue<never>;
//   ^? type SurpriseParty = 'Huzzah!'
```

**Probably, it's safe to conclude that whenever we prevent the distribution behaviour we'd have to be mindful of how we want `never` to be handled?** 

## Distribution over unions only works when the union is on the LHS

So, in [Item 53](https://github.com/danvk/effective-typescript/blob/main/samples/ch-generics/control-distribution.md), there's this `NTuple` type:

```ts
type NTuple<T, N extends number> = NTupleHelp<T, N, []>;

type NTupleHelp<T, N extends number, Acc extends T[]> =
  Acc['length'] extends N
  ? Acc
  : NTupleHelp<T, N, [T, ...Acc]>;

type PairOrTriple = NTuple<bigint, 2 | 3>
//   ^? PairOrTriple = [bigint, bigint] 
```

Now this doesn't yield the desired results when `N` is a union, like `2 | 3`, and the book gives the following explanation for the same:
```
The problem is that the condition is `Acc['length']` extends `N`, which does not start with the bare "N extends..." that's required for the distribution.
```  
This line feels a bit confusing to me because the distribution here is not related to bareness but because the union (N) type is not on the LHS but on the RHS. **What are your thoughts on this?**
Which also means that the easiest solution here is to just flip the conditional from `Acc['length'] extends N` to `N extends Acc['length']` instead of adding an extra conditional.

```ts
type NTuple<T, N extends number> = NTupleHelp<T, N, []>;

type NTupleHelp<T, N extends number, Acc extends T[]> =
  N extends Acc['length']
  ? Acc
  : NTupleHelp<T, N, [T, ...Acc]>;

type PairOrTriple = NTuple<bigint, 2 | 3>
//   ^? PairOrTriple = [bigint, bigint] | [bigint, bigint, bigint]
```

Thanks!!

**Comment by ssmkhrj** [comment]
@danvk Would really appreciate if you check this out once and let me your thoughts.

**Comment by danvk** [comment]
Hey @ssmkhrj thanks for the questions! And thanks for reading the book, I'm really happy to hear it's been a wonderful experience!

At a high level, I think you've gotten the right message that you should think about distribution and `never` whenever you're working with conditional types.

For the specifics:

`Comparable<T>`

I think you're right that we want `Comparable<never>` to be `never`. This follows from its use in `isLessThan`:

```ts
declare let n: never;
isLessThan(n, new Date());  // should be an error!
```

So yes, I should mention this. I'm afraid it will have to be in a footnote since the discussion of `never` comes later in the item.

`CelebrateIfTrue<V>`

Yes, I think you're right. If we want it to be "Huzzah!" only if `V` is _equal_ to `true`, then we need to either check for `[never]` explicitly (since this is the only subtype of `true`) or do a two-way check:

```ts
type CelebrateIfTrue<V> = [V] extends [true] ? true extends V ? 'Huzzah!' : never : never;

type CNever = CelebrateIfTrue<never>;
//   ^? type CNever = never
type CTrue = CelebrateIfTrue<true>;
//   ^? type CTrue = "Huzzah!"
type CFalse = CelebrateIfTrue<false>;
//   ^? type CFalse = never
type CBool = CelebrateIfTrue<boolean>;
//   ^? type CBool = never
```

Type equality is usually not what you want, but in the rare cases where it is, this can be a handy trick!

`NTuple`

Flipping the conditional does work for that example. But here's another problem:

```ts

type NTuple<T, N extends number> = NTupleHelp<T, N, []>;

type NTupleHelp<T, N extends number, Acc extends T[]> =
  N extends Acc['length']
  ? Acc
  : NTupleHelp<T, N, [T, ...Acc]>;

type FootnoteClaim = NTuple<string, number>;
//                   ~~~~~~~~~~~~~~~~~~~~~~
// Type instantiation is excessively deep and possibly infinite. (2589)
```

Of course, the book's solution gives the wrong result in this case, so you'd still need to special-case `number` either way.

---

Hope that helps! You've given these items an impressively thorough read — none of my technical reviewers (some of whom are on the TypeScript team) noticed any of these issues.

**Comment by som-sm** [comment]
Yeah, that helped—appreciate your reply!
